### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by dieghernan** [welcomments/website#2]
Hi @roughike 

As you already know, I implemented welcomments on https://dieghernan.github.io/chulapa/docs/02-config#xx-other-settings

I share here with you some thoughs:

## On the bot

- AFAIK there is no way to tell Welcomments that the site is being deployed from a folder. Say, Chulapa docs (Jekyll) are deployed from https://github.com/dieghernan/chulapa/tree/master/docs but the bot commited to `./_data`  instead to `./docs/_data`. Then, on the site deployment the comments are gathered via your js plugin and not from the local storage on GitHub. So If a user with this setup opts out of the js plugin the comments are not shown, since Jekyll would look for data on `docs/_data`. My workaround was to move the content from `_data` to `docs/data`.

## On the templates
- At least on Jekyll, the current template does not make use of `author website`. I think this is easy to fix on the templates with something like

```
        <h3 class="welcomments__author-name" itemprop="author" itemscope itemtype="https://schema.org/Person">
        {% if author_website %}
          <span itemprop="name"><a href ="{{ author_website }}"> {{ author_name }}</a></span>
        {% else %}
       <span itemprop="name">{{ author_name }}</span>
        {% endif %}
        </h3>
```

A new css rule would be needed, something like

```css
.welcomments__container .welcomments__author-name a:hover {
    text-decoration: underline;
    background: none;
}
```

## On the css

I noticed that the custom css https://cdn.welcomments.io/welcomments.css interacts badly with Fontawesome, basically due to this kind of rules:

```css

.welcomments__container * {
    font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
    line-height: 1.5;
}
.welcomments__container * {
    font-family: inherit;
    line-height: inherit;
}
...


```

In my case I needed to ship a modified version of the welcomments removing the font-family rules.

## Misc

On avatar image, welcomments seems to be ready to use custom images but it is not integrated (at least not in the customr form). My understanding is that providing a form for inputting an url to an avatar is easy. Would it be something that you may consider to expand?

Regards and thanks for this coooool plugin
